### ISSUE TITLE
Ты гандон, нихуя не работает

### ISSUE THREAD

**Issue by hto-ya** [Ruthercode/vk_bot#7]
просили - сделали
а, вообще, я плачу (от счастья) из-за добавление Cыктывкар'a
Название звучит, как что-то среднее между чем-то казахским и птицей (не примите за оскорбление казахов)
А так, жду фичи (не баги)

**Comment by Kibermuzhik** [comment]
### **РУКИ ПРОЧЬ ОТ КАЗАХСТАНА**

**Comment by hto-ya** [comment]
казах детектед
